### ISSUE TITLE
New component: SunEditor

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions#1110]
Pure javscript based WYSIWYG web editor, with no dependencies.

MIT Licensed: https://github.com/JiHong88/suneditor

To replace the removed CKEditor for WYSIWYG editing.

- [ ] Theme switching https://github.com/JiHong88/suneditor/issues/978
- [x] Sanitizing like TextEditor
- [x] Extender support
- [x] Test inside dialog
- [x] Right-To-Left Support
- [x] Button assignment using JSON?
- [x] Showcase examples including Locale switching

**Comment by melloware** [comment]
We could do it similar to CKEditor where all the dependencies are in a submodule if its a large amount of JS code.  If it is not that large we can just make it a core component.

**Comment by jepsar** [comment]
Yeah, that would be the idea, as the minified JS is huge.

**Comment by fcorneli** [comment]
My two cents here. Within `ejsf` I directly isolated all external resources within separate JARs. This strategy brings several advantages:
* obviously a smaller core taglib JAR, and hence your WARs/EARs remain as small as possible, safeguarding build and deployment time.
* because all `npm` stuff lives outside the core taglib, the development-deployment cycle improves drastically for the component development itself.
* cleaner core taglib `pom.xml`

Looking at `primefaces-extensions`, there are several candidates to put the core taglib JAR like on a diet. Most prominent here is `documentviewer` I guess.

One could argue that for `primefaces` itself, having a single JAR makes it easier for newbies to get started. However, if I look at all the craziness required for "modern" JS based frameworks to get started, I doubt that this still holds as strong selling point. As for `primefaces-extensions`, I guess it's safe to assume that the audience here is capable of including an extra JAR every now and then.

**Comment by melloware** [comment]
For me personally I don't care much about JAR size as disk space of deployments is cheap.  I more care about what JS gets sent to the browser and for PFE every single component only sends its JS to the browser where in PF it packs a bunch of components into components.js.  I know why PF does it but I use OmniFaces CombinedResourceHandler so for me it would be more efficient if PF did the same as PFE and only send the components you were using to the browser!

But I know enforcing that requirement is not possible.

**Comment by MatthSHo** [comment]
Great alternative to CKeditor ;)

**Comment by melloware** [comment]
Thanks @MatthSHo for doing the heavy lifting.  Its much easier for us to clean up and modify a component than to start with nothing!
