### ISSUE TITLE
Sheet: Allow cell editing facets

### ISSUE THREAD

**Issue by anatoliaDev** [primefaces-extensions/primefaces-extensions#1209]
### Describe the feature you would like to see added

I would like to use f:facet functionality for sheet table like how normal primefaces datatable supports celleditor. Like input and output. LiKE  ```
<pe:sheetcolumn headerText="Product Category" value="#{material.productCategory}"  colWidth="200"
                        colType="dropdown"
                        selectItems="#{Bean.getMapItems('productCategory')}">
            <p:cellEditor>
                <f:facet name="output"><h:outputText value="TEST" /></f:facet>
                <f:facet name="input"><p:inputText id="modelInput" value="#{material.productCategory}"/></f:facet>
            </p:cellEditor>
        </pe:sheetcolumn>
```

### Is your feature request related to a problem?

_No response_

### Describe the solution you'd like

_No response_

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

**Comment by melloware** [comment]
Due to the nature of the HandsonTable and how the sheet works this is not currently possible.  Cell renderer's are currently on the whole column and could not be tweaked per cell and it would take a significant rewrite to make this happen.  Even then I am not sure it would work properly as the Sheet must re-render the whole sheet every time a renderer would change which would be a terrible UI/UX experience.  So I am going to mark this as Wont Fix.
