### ISSUE TITLE
Sheet: New column type "button"

### ISSUE THREAD

**Issue by ssibitz** [primefaces-extensions/primefaces-extensions#136]
In the newest component "Sheet" i am missing a ColType for handling button-actions
like Delete Row, Mark Row and so on.

I will eventually need this for our project because in the showcase 
the example for using it with right-click is nice, 
but not useable on e.g. a touch-screen
or a user who don't know how to use the right-click ;-)

Here would it always be better to support a button with a minimum height of
about 39px, a icon (font awesome if possible) and a listener or onclick .

**Comment by melloware** [comment]
I like the idea of a button cell.    Just have to figure out how to implement.  Looks like I will have to use HTML cell type...

https://stackoverflow.com/questions/24774811/how-do-i-add-a-custom-button-inside-a-cell-in-handsontable/24777491

And all the reasons you stated above is why we built the sheet component because we had similar requirements to yours and with Datatable would run into Form parameters limits etc.

**Comment by melloware** [comment]
I am not planning on adding this. Will reopen if someone submits a PR down the road.
