### ISSUE TITLE
Document Viewer: component not rendering some PDF files correctly

### ISSUE THREAD

**Issue by EltonR** [primefaces-extensions/primefaces-extensions#557]
**Describe the bug**
Some files don't render correctly on component Document Viewer, althought they do render OK on PDF.JS
[2 POSTO TURMALINA III.pdf](https://github.com/primefaces-extensions/primefaces-extensions/files/7220610/2.POSTO.TURMALINA.III.pdf)

**Environment:**
 - PF Version: 10.0, Extensions 10.0.5, Java 8, Wildfly 10

**To Reproduce**
Open the link bellow, then on the viewer choose "Open", and select the attached file. Then you can see what seems to be a gray overlay. Note that you can even select the text... 
https://www.primefaces.org/showcase-ext/sections/documentviewer/advanced.jsf

**Expected behavior**
The document should render normally, as it renders on any other pdf viewer.

**Comment by melloware** [comment]
Your error in F12 console `Warning: JPX: Trying to recover from: "JPX error: Out of packets`

Your error is a Mozilla PDF.js error: https://github.com/mozilla/pdf.js/issues/11957

Looks like someone submitted a fix recently: https://github.com/mozilla/pdf.js/pull/13698 but it has not been released.  We are using the release from May 2021 and this bug was only fixed in the last couple of weeks and no new PDF.JS release has been done yet.

Similar to this forum post: https://forum.primefaces.org/viewtopic.php?f=14&t=68362&start=10

**Comment by melloware** [comment]
You can go upvote this issue for a new release: https://github.com/mozilla/pdf.js/issues/14001

**Comment by melloware** [comment]
OK this will be fixed in 10.0.7 and 11.0.0.  I verified your PDF above now renders correctly!

**Comment by EltonR** [comment]
> OK this will be fixed in 10.0.7 and 11.0.0. I verified your PDF above now renders correctly!

Thank you very much!

**Comment by melloware** [comment]
8.0.5 and 10.0.7 with this fix have been released to Maven Central.
