### ISSUE TITLE
MonacoEditor: Add FreeMarker language and example

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#710]
Now that Monacoeditor 0.32 is released we need to add Freemarker to the list of languages and examples.

cc @blutorange

**Comment by blutorange** [comment]
We don't need to add it in the sense that the `EditorOptions#setLanguage`  also takes a string, so it would already work by updating the monaco dependency.

But there's an enum for convenience, which should be amended, and we should also add a code example to the showcase.

**Comment by melloware** [comment]
yep i saw the enum and figured we should update.

**Comment by melloware** [comment]
I am messing around with it and it looks like its not highlighing my `$` directives only my `#` directives?

![image](https://user-images.githubusercontent.com/4399574/152644588-307d1e6f-d09b-4a9b-9b4e-d196584c6d86.png)

**Comment by blutorange** [comment]
@melloware Iirc it's basically this:

> This demonstrates the FreeMarker language. The default theme is not very
colorful and displays many different token types in the same color, but keep in
mind that you can define your own theme (or extend an existing one).
>
> Do
> 
> Right click -> Command Palette -> > Developer: Inspect Tokens
>
> to see the token name to use with the custom theme.

The tokenizer splits this into different tokens, but the default theme simply doesn't specify any colors for those tokens. That's why I applied a custom theme to the demonstration I made before submitting it to the Monaco editor repo.

You can define a custom theme via Java, see the custom theme showcase:

```java
    /**
     * @return The custom theme for the showcase illustrating how to add a custom theme to the Monaco editor.
     */
    public static EditorStandaloneTheme createDemoCustomTheme() {
        return new EditorStandaloneTheme() //
                    .setBase(ETheme.VS) //
                    .setInherit(true) //
                    .setRules(Arrays.asList( //
                                new EditorTokenThemeRule().setToken("comment").setForeground("ffa500").setFontStyle("italic underline"), //
                                new EditorTokenThemeRule().setToken("comment.js").setForeground("008800").setFontStyle("bold"), //
                                new EditorTokenThemeRule().setToken("comment.css").setForeground("0000ff") //
                    ));
    }
``` 

![image](https://user-images.githubusercontent.com/2456413/152646639-c163e42a-9070-4f63-8bea-51e37bddd5d3.png)

**Comment by melloware** [comment]
Ok yeah let me look at this because I will need to create light and dark themes for freemarker to show the syntax highlighted templates.
