### ISSUE TITLE
CreditCard: Not working in Carousel

### ISSUE THREAD

**Issue by mortadha-dev** [primefaces-extensions/primefaces-extensions#838]
### Describe the bug

Color of card dissapear when putting a list of credit cards in a  <p:carousel> 

### Reproducer

[primefaces-test.zip](https://github.com/primefaces-extensions/primefaces-extensions/files/8747416/primefaces-test.zip)

### Expected behavior

Color of credit card should appear

### PrimeFaces Extensions version

11.0.3

### JSF implementation

MyFaces

### JSF version

2.3.9

**Comment by melloware** [comment]
OK so this is a difficult one.  The CreditCard is meant to only have one on the screen at a time.  It uses `prependId="false` so the input fields get names like `name="cvc"` and not `"name="jidt310:cvc"` typical JSF names because the way the credit card component looks for its default 4 fields.

However when using in a Carousel it needs to add the index ID to make the fields unique to prevent duplicate ID's in the DOM so the values of your example are `name="j_idt10:0:cvc"` and `name="j_idt10:1:cvc"` so the Card JS is not properly finding the fields and in fact Card 2 is displaying the values of Card 1 in your example.

So for now I will say because of how its designed I don't think this will work in a Carousel. At least not without a major refactoring of the Card component to try and handle this scenario.

**Comment by melloware** [comment]
Going to close this as WontFix
