### ISSUE TITLE
Monaco: JS error in PF 12

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions#968]
### Describe the bug

Forum Post: https://forum.primefaces.org/viewtopic.php?f=14&t=77299&

Go to Showcase: https://www.primefaces.org/showcase-ext/sections/monacoEditor/basicUsage.jsf

![image](https://user-images.githubusercontent.com/4399574/195368936-d9063f1d-e5d0-4ed6-8c42-e403072bca8a.png)

cc @blutorange 

### PrimeFaces Extensions version

12.0.0

### JSF implementation

All

### JSF version

2.3

### Browser(s)

ALL

**Comment by melloware** [comment]
I have a feeling it was the updated from Monaco 0.33 to 0.34 that might have broken it?

**Comment by blutorange** [comment]
We [overwrite](https://github.com/primefaces-extensions/primefaces-extensions/blob/master/monacoeditor/src/main/js/nls-replace.js) the file [nls.js](https://unpkg.com/monaco-editor@0.34.0/esm/vs/nls.js) to support (dynamic) localization. This file [has changed quite a bit](https://unpkg.com/monaco-editor@0.33.0/esm/vs/nls.js) since version 0.33, our overwrite is now missing functions.

**Comment by melloware** [comment]
Should I roll back to 0.33 for now?

**Comment by blutorange** [comment]
I can take a look a closer this during the weekend. So unless you want to release a fixed version in the next few days, I don't think you need to.

**Comment by melloware** [comment]
ok cool you rock!
